#!/bin/sh
########################################################################
# Begin $network_devices/services/mtu
#
# Description : Sets MTU per interface
#
# Authors     : Nathan Coulson - nathan@linuxfromscratch.org
#		Jim Gifford - jim@linuxfromscratch.org
#
# Version     : 00.00
#
# Notes       : This sets the maximum amount of bytes that can be
#		transmitted within a packet.  By default, this
#		value is set to 1500.
#
########################################################################

. /etc/sysconfig/rc 
. ${rc_functions}
. ${IFCONFIG}

if [ -z "${MTU}" ]
then
	boot_mesg "MTU variable missing from ${IFCONFIG}, cannot continue." ${FAILURE}
	echo_failure
	exit 1
fi

case "${2}" in
	up)
		boot_mesg "Setting the MTU for ${1} to ${MTU}..."
		echo "${MTU}" > "/sys/class/net/${1}/mtu"
		evaluate_retval
	;;
	
	down)
	;;
	
	*)
		echo "Usage: ${0} [interface] {up|down}"
		exit 1
	;;
esac

# End $network_devices/services/mtu
