#!/bin/bash
###############################################################################
#                                                                             #
# File:        entResolver                                                    #
#                                                                             #
# Description: Works around libxml2 bug 135713 by preprocessing entity        #
#              references before performing any stylesheet processing.        #
#                                                                             #
# Author:      Manuel Canales Esparcia                                        #
#                                                                             #
###############################################################################

NAME=`basename "$0"`
DESTDIR="$1"

if [ -z "$1" ]; then
        echo "USAGE: $NAME destdir"
        exit
fi

mkdir -p ../"$DESTDIR"/chapter0{1,2,3,4,5,6,7,8,9}
mkdir -p ../"$DESTDIR"/prologue
mkdir -p ../"$DESTDIR"/appendix{a,b}

for i in `find . -name "*.xml"`; do
        xmllint --nonet --noent "${i}" > ../"$DESTDIR"/"${i}";
done

cp -a stylesheets ../"$DESTDIR"
