#!/bin/sh
# Begin $RC_BASE/init.d/mountvirtfs

### BEGIN INIT INFO
# Provides:            mountvirtfs
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       S
# Default-Stop:
# Short-Description:   Mounts /sys, /proc, and /run virtual (kernel) filesystems.
# Description:         Mounts /sys, /proc, and run  virtual (kernel) filesystems.
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /lib/lsb/init-functions

case "${1}" in
    start)
        message="Mounting virtual file systems:"

        if ! mountpoint /proc > /dev/null; then
            message="${message}${INFO} /proc${NORMAL}"
            mount -n /proc || failed=1
        fi

        if ! mountpoint /sys > /dev/null; then
            message="${message}${INFO} /sys${NORMAL}"
            mount -n /sys || failed=1
        fi

        # create needed directories in /run
        mkdir /run/{var,lock,shm} || failed=1
        chmod 1777 /run/shm

        (exit ${failed})
        evaluate_retval standard
        ;;

    *)
        echo "Usage: ${0} {start}"
        exit 1
        ;;
esac

# End $RC_BASE/init.d/mountvirtfs
