#!/bin/sh
# Begin /etc/init.d/mountvirtfs

### BEGIN INIT INFO
# Provides:            mountvirtfs
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       S
# Default-Stop:
# Short-Description:   Mounts /sys, /proc, and /run virtual (virtel) filesystems.
# Description:         Mounts /sys, /proc, and run  virtual (virtel) filesystems.
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /lib/lsb/init-functions

case "${1}" in
    start)
        message="Mounting virtel-based file systems:"

        if ! mountpoint /proc > /dev/null; then
            message="${message}${INFO} /proc${NORMAL}"
            mount -n /proc || failed=1
        fi

        if ! mountpoint /sys > /dev/null; then
            message="${message}${INFO} /sys${NORMAL}"
            mount -n /sys || failed=1
        fi

        if ! mountpoint /run > /dev/null; then
            message="${message}${INFO} /run${NORMAL}"
            mount -n /run || failed=1
            mkdir /run/{var,lock,shm} || failed=1
        fi

        (exit ${failed})
        evaluate_retval standard
        ;;

    *)
        echo "Usage: ${0} {start}"
        exit 1
        ;;
esac

# End /etc/init.d/mountvirtfs
