#!/bin/sh
########################################################################
# Begin mountvirtfs
#
# Description : Mount proc, sysfs, and run
#
# Authors     : Gerard Beekmans - gerard@linuxfromscratch.org
# Update      : Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            mountvirtfs
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       S
# Default-Stop:
# Short-Description:   Mounts /sys and /proc virtual (kernel) filesystems.
#                      Mounts /run tmpfs.
# Description:         Mounts /sys and /proc virtual (kernel) filesystems.
#                      Mounts /run tmpfs.
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /lib/boot/functions

case "${1}" in
   start)
      mkdir -p /run
      mount -n /run || failed=1
      mkdir -p /run/{var,lock,shm}


      boot_mesg -n "Mounting virtual file systems:" ${INFO}
      boot_mesg -n " /run" ${NORMAL}

      if ! mountpoint /proc >/dev/null; then
         boot_mesg -n " /proc" ${NORMAL}
         mount -n /proc || failed=1
      fi

      if ! mountpoint /sys >/dev/null; then
         boot_mesg -n " /sys" ${NORMAL}
         mount -n /sys || failed=1
      fi

      boot_mesg "" ${NORMAL}

      (exit ${failed})
      evaluate_retval
      ;;

   *)
      echo "Usage: ${0} {start}"
      exit 1
      ;;
esac

# End mountvertfs
