#!/bin/sh
########################################################################
# Begin $rc_base/init.d/mountvirtfs
#
# Description : Mount proc, sysfs, and run
#
# Authors     : Gerard Beekmans - gerard@linuxfromscratch.org
#
# Version     : 00.00
#
# Notes       :
#
########################################################################

. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	start)
		boot_mesg -n "Mounting virtual file systems:" ${INFO}

		if ! mountpoint /proc >/dev/null; then
			boot_mesg -n " /proc" ${NORMAL}
			mount -n /proc || failed=1
		fi

		if ! mountpoint /sys >/dev/null; then
			boot_mesg -n " /sys" ${NORMAL}
			mount -n /sys || failed=1
		fi

		if ! mountpoint /run >/dev/null; then
			boot_mesg -n " /run" ${NORMAL}
			mount -n /run || failed=1
			mkdir /run/var
			mkdir /run/shm
		fi

		boot_mesg "" ${NORMAL}

		(exit ${failed})
		evaluate_retval
		;;

	*)
		echo "Usage: ${0} {start}"
		exit 1
		;;
esac

# End $rc_base/init.d/mountvertfs
