#!/bin/sh
########################################################################
# Begin sysklogd
#
# Description : Sysklogd loader
#
# Authors     : Gerard Beekmans - gerard@linuxfromscratch.org
# Update      : Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            $syslog
# Required-Start:      localnet
# Should-Start:
# Required-Stop:       $local_fs sendsignals
# Should-Stop:
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Starts kernel and system log daemons.
# Description:         Starts kernel and system log daemons.
#                      /etc/fstab.
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /lib/boot/functions

case "${1}" in
   start)
      boot_mesg "Starting system log daemon..."
      PARMS=${SYSKLOGD_PARMS-'-m 0'}
      loadproc syslogd $PARMS

      boot_mesg "Starting kernel log daemon..."
      loadproc klogd
      ;;

   stop)
      boot_mesg "Stopping kernel log daemon..."
      killproc klogd

      boot_mesg "Stopping system log daemon..."
      killproc syslogd
      ;;

   reload)
      boot_mesg "Reloading system log daemon config file..."
      reloadproc syslogd
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   status)
      statusproc syslogd
      statusproc klogd
      ;;

   *)
      echo "Usage: ${0} {start|stop|reload|restart|status}"
      exit 1
      ;;
esac

# End sysklogd
