#!/bin/sh
# Begin $RC_BASE/init.d/sendsignals

### BEGIN INIT INFO
# Provides:            sendsignals
# Required-Start:
# Should-Start:
# Required-Stop:       $local_fs swap localnet
# Should-Stop:
# Default-Start:
# Default-Stop:        0 6
# Short-Description:   Attempts to kill remaining processes.
# Description:         Attempts to kill remaining processes.
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /lib/lsb/init-functions

case "${1}" in
    stop)
        message="Sending all processes the TERM signal..."
        killall5 -15
        error_value=${?}
        # Account for successful return value of 2
        if [ ${error_value} -eq 2 ]; then
            error_value=0
        fi
        sleep 3

        (exit ${error_value})
        evaluate_retval standard

        message="Sending all processes the KILL signal..."
        killall5 -9
        error_value=${?}
        # Account for successful return value of 2
        if [ ${error_value} -eq 2 ]; then
            error_value=0
        fi

        sleep 3

        (exit ${error_value})
        evaluate_retval standard
        ;;

    *)
        echo "Usage: ${0} {stop}"
        exit 1
        ;;

esac

# End $RC_BASE/init.d/sendsignals
