#!/bin/sh
# Begin $RC_BASE/init.d/setclock

### BEGIN INIT INFO
# Provides:            hwclock
# Required-Start:
# Should-Start:        modules
# Required-Stop:
# Should-Stop:         $syslog
# Default-Start: 
# Default-Stop: 
# Short-Description:   Stores and restores time from the hardware clock
# Description:         On boot, system time is obtained from hwclock.  The
#                      hardware clock can also be set on shutdown.
# X-LFS-Provided-By:   LFS BLFS
### END INIT INFO

. /lib/lsb/init-functions

BIN_FILE="/sbin/hwclock"

chk_stat

case "${UTC}" in
    yes|true|1)
        CLOCKPARAMS="${CLOCKPARAMS} --utc"
        ;;

    no|false|0)
        CLOCKPARAMS="${CLOCKPARAMS} --localtime"
        ;;

esac

case ${1} in
    start)
        message="Setting system clock..."
        ${BIN_FILE} --hctosys ${CLOCKPARAMS} >/dev/null
        evaluate_retval standard
        ;;

    stop)
        message="Setting hardware clock..."
        ${BIN_FILE} --systohc ${CLOCKPARAMS} >/dev/null
        evaluate_retval standard
        ;;

    *)
        echo "Usage: ${0} {start|stop}"
        ;;

esac

# End $RC_BASE/init.d/setclock
