#!/bin/sh
# Begin /etc/init.d/mountkernfs

### BEGIN INIT INFO
# Provides:            mountkernfs
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       S
# Default-Stop:
# Short-Description:   Mounts /sys and /proc virtual (kernel) filesystems.
# Description:         Mounts /sys and /proc virtual (kernel) filesystems.
# X-LFS-Default-Start: S00
# X-LFS-Default-Stop:
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /lib/lsb/init-functions

case "${1}" in
    start)
        message="Mounting kernel-based file systems:"

        if ! mountpoint /proc > /dev/null; then
            message="${message}${INFO} /proc${NORMAL}"
            mount -n /proc || failed=1
        fi

        if ! mountpoint /sys > /dev/null; then
            message="${message}${INFO} /sys${NORMAL}"
            mount -n /sys || failed=1
        fi

        (exit ${failed})
        evaluate_retval standard
        ;;

    *)
        echo "Usage: ${0} {start}"
        exit 1
        ;;
esac

# End /etc/init.d/mountkernfs
