#!/bin/sh
# Begin /etc/init.d/sendsignals

### BEGIN INIT INFO
# Provides:            sendsignals
# Required-Start:
# Should-Start:
# Required-Stop:       $local_fs swap localnet
# Should-Stop:         halt reboot
# Default-Start:       0 6
# Default-Stop:
# Short-Description:   Attempts to kill remaining processes.
# Description:         Attempts to kill remaining processes.
# X-LFS-Default-Start:
# X-LFS-Default-Stop:  S60
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /lib/lsb/init-functions

case "${1}" in
    stop)
        message="Sending all processes the TERM signal..."
        killall5 -15
        error_value=${?}

        sleep 3

        (exit ${error_value})
        evaluate_retval standard

        message="Sending all processes the KILL signal..."
        killall5 -9
        error_value=${?}

        sleep 3

        (exit ${error_value})
        evaluate_retval standard
        ;;

    *)
        echo "Usage: ${0} {stop}"
        exit 1
        ;;

esac

# End /etc/init.d/sendsignals
