#!/bin/bash
#######################################################################
#
# File:        goTidy
#
# Description: Tidy is best used inside a loop, but Makefiles don't do
# bash loops well.  This file alleviates that problem.
#
# Author:      James Robertson
#
########################################################################

for file in `find "$1" -name "*.html"`; do
        tidy -config tidy.conf $file
done

exit 0
